title: "Élodie HEINRY | Data Analyste"
description: "Data Analyste Junior spécialisée en Power BI, Python et analyse de données"
baseurl: ""
url: "https://elo3534.github.io"
lang: fr

# Thème GitHub Pages officiel Minimal
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Logo (évite les espaces dans le nom de fichier)
logo: assets/images/logo.png

# Infos perso
name: "Élodie HEINRY"
email: "heinryelodie@hotmail.fr"
phone: "06 18 70 42 77"
location: "Montpellier"
linkedin: "elodie-heinry"
github: "Elo3534"

# Navigation
header_pages:
  - index.md
  - about.md
  - experience.md
  - skills.md
  - projects.md
  - contact.md

# Liens sociaux
social:
  - name: LinkedIn
    icon: linkedin
    url: https://linkedin.com/in/elodie-heinry
  - name: GitHub
    icon: github
    url: https://github.com/Elo3534

# Paramètres Markdown
markdown: kramdown

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

  - vendor/ruby/
