# _config.yml pour le thème modernist v0.2.2

# Informations du site
title: "Mon Portfolio"
description: "Bienvenue sur mon portfolio !"
baseurl: ""  # mettre "" si le site est à la racine, sinon "/monrepo"
url: "https://Elo3534.github.io" # Remplacez par votre URL GitHub Pages

# Thème
remote_theme: pages-themes/modernist@v0.2.2
plugins:
  - jekyll-remote-theme

# Options du thème
show_downloads: false

# Informations personnelles
author:
  name: "Elodie HEINRY"
  email: "heinryelodie@hotmail.fr"
  github: "Elo3534"
  linkedin: "https://www.linkedin.com/in/elodie-heinry" # Optionnel
  
# Navigation
nav:
  - name: "Accueil"
    link: "/"
  - name: "Projets"
    link: "/projets"
  - name: "À propos"
    link: "/about"
  - name: "Contact"
    link: "/contact"

# Plugins recommandés
plugins:
  - jekyll-feed
  - jekyll-seo-tag
